### ISSUE TITLE
Calling sqrt builtin function for packed singles instead of packed doubles

### ISSUE THREAD

**Issue by maximiliank** [GSI-HPC/simd#9]
The following example code does not compile with g++ 14.2.0 (No specific -march parameter):

```cpp
#include <simd>
#include <vector>

int main()
{
    std::vector<double> data(std::datapar::simd<double>::size(), 0.05);
    std::datapar::simd<double> x = std::datapar::unchecked_load(data);
    auto xSqrt = std::datapar::sqrt(x);

    return 0;
}
``` 
The error message:
```
bits/simd_x86.h:2424:42: error: cannot convert ‘__vector(2) double’ to ‘__vector(4) float’
[build]  2424 |             return __builtin_ia32_sqrtps(__x);
[build]       |                                          ^~~
[build]       |                                          |
[build]       |                                          __vector(2) double
[build] <built-in>: note:   initializing argument 1 of ‘__vector(4) float __builtin_ia32_sqrtps(__vector(4) float)’
```
The wrong builtin function for ` sqrt`  is called and should be replaced with `__builtin_ia32_sqrtpd`  for packed doubles:
https://github.com/GSI-HPC/simd/blob/91a4477dd70145f6dc3f070601005117e99a3e06/bits/simd_x86.h#L2424
